version: '3'
services:

  nginx:
    image: nginx:latest
    volumes:
      - ./public:/public
      - ./site.conf:/etc/nginx/conf.d/default.conf
    networks: 
      codeigniter_net:
    ports:
      - "8181:90"
    restart: always

  php:
    build: 
      context: ./public
      dockerfile: Dockerfile
    volumes:
      - ./public:/public
    depends_on:
      - database
    networks:
      codeigniter_net:

  database:
    image: mysql:5.7
    networks:
      codeigniter_net:
    ports:
      - 3306:3306
    env_file:
      - .env

  phpmyadmin:
    depends_on:
      - database
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8282:80'
    env_file:
      - .env
    networks:
      codeigniter_net:

networks:
  codeigniter_net:
